# @package _global_

defaults:
  - base

robot:
  body_names: ['torso_link', 'pelvis', 'R_hipyaw_link', 'R_hiproll_link', 'R_hippitch_link', 'R_shank_link', 'R_ankle_link', 'R_foot_link', 'R_toe_link', 'L_hipyaw_link', 'L_hiproll_link', 'L_hippitch_link', 'L_shank_link', 'L_ankle_link', 'L_foot_link', 'L_toe_link']
  dof_names: ['torsoyaw', 'R_hipyaw', 'R_hiproll', 'R_hippitch', 'R_knee', 'R_anklepitch', 'R_ankleroll', 'R_toepitch', 'L_hipyaw', 'L_hiproll', 'L_hippitch', 'L_knee', 'L_anklepitch', 'L_ankleroll', 'L_toepitch']

  trackable_bodies_subset: ['pelvis', 'head', 'left_ankle_link', 'right_ankle_link']

  # Observation parameters
  dof_obs_size: ${eval:${len:${.dof_body_ids}}*6}
  number_of_actions: 15
  self_obs_max_coords_size: 238  # ${eval:1+33*(3+6+3+3)-3}

  # Control parameters
  dof_body_ids: [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]
  dof_effort_limits: [88.0, 88.0, 88.0, 139.0, 50.0, 50.0, 88.0, 88.0, 88.0, 139.0, 50.0, 50.0, 88.0, 50.0, 50.0]
  dof_vel_limits: [32.0, 32.0, 32.0, 20.0, 37.0, 37.0, 32.0, 32.0, 32.0, 20.0, 37.0, 37.0, 32.0, 37.0, 37.0]
  dof_armatures: [0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03]
  dof_joint_frictions: [0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03]

  key_bodies: [ "R_foot_link", "L_foot_link" ]
  non_termination_contact_bodies: ['torso_link', 'pelvis', 'R_hipyaw_link', 'R_hiproll_link', 'R_hippitch_link', 'R_shank_link', 'R_ankle_link', 'R_foot_link', 'R_toe_link', 'L_hipyaw_link', 'L_hiproll_link', 'L_hippitch_link', 'L_shank_link', 'L_ankle_link', 'L_foot_link', 'L_toe_link']
  right_foot_name: "R_foot_link"
  left_foot_name: "L_foot_link"
  head_body_name: "torso_link"

  init_state:
    pos: [0.0, 0.0, 0.8] # x,y,z [m]
    default_joint_angles: # = target angles [rad] when action = 0.0
      # These bias the controller and are recommended to be set at 0.
      torsoyaw: 0.
      R_hipyaw: 0.
      R_hiproll: 0.
      R_hippitch: 0.
      R_knee: 0.
      R_anklepitch: 0.
      R_ankleroll: 0.
      R_toepitch: 0.
      L_hipyaw: 0.
      L_hiproll: 0.
      L_hippitch: 0.
      L_knee: 0.
      L_anklepitch: 0.
      L_ankleroll: 0.
      L_toepitch: 0.

  control:
    control_type: proportional
    use_biased_controller: False  # See default_joint_angles
    map_actions_to_pd_range: True
    # PD Drive parameters:
    stiffness: # [N*m/rad]
      torsoyaw: 100.
      R_hipyaw: 100.
      R_hiproll: 100.
      R_hippitch: 100.
      R_knee: 100.
      R_anklepitch: 100.
      R_ankleroll: 100.
      R_toepitch: 100.
      L_hipyaw: 100.
      L_hiproll: 100.
      L_hippitch: 100.
      L_knee: 100.
      L_anklepitch: 100.
      L_ankleroll: 100.
      L_toepitch: 100.
    damping: # [N*m/rad]  # [N*m*s/rad]
      torsoyaw: 10.
      R_hipyaw: 10.
      R_hiproll: 10.
      R_hippitch: 10.
      R_knee: 10.
      R_anklepitch: 10.
      R_ankleroll: 10.
      R_toepitch: 10.
      L_hipyaw: 10.
      L_hiproll: 10.
      L_hippitch: 10.
      L_knee: 10.
      L_anklepitch: 10.
      L_ankleroll: 10.
      L_toepitch: 10.

  asset:
    collapse_fixed_joints: True # merge bodies connected by fixed joints. Specific fixed joints can be kept by adding " <... dont_collapse="true">
    replace_cylinder_with_capsule: True
    flip_visual_attachments: False
    armature: 0.001
    thickness: 0.01
    max_angular_velocity: 1000.
    max_linear_velocity: 1000.
    density: 0.001
    angular_damping: 0.
    linear_damping: 0.

    asset_file_name: "urdf/prestoe_biped.urdf"
    usd_asset_file_name: "usd/prestoe_biped.usd"
    robot_type: prestoe_biped
    self_collisions: False
    default_dof_drive_mode: 3

  sim:
    isaacgym:
      fps: 200
      decimation: 4
      substeps: 1
    isaaclab:
      fps: 200
      decimation: 4
    genesis:
      fps: 200
      decimation: 4
      substeps: 1


# Override motion lib default to use the adapted H1 variant
motion_lib:
  _target_: protomotions.utils.motion_lib_h1.H1_MotionLib

# Override simulation config to use the adapted H1 variant
env:
  config:
    mimic_reset_track:
      grace_period: 10
